# PYTHON PACKAGES

# MOTIVATION
# ___________
# FUNCTIONS AND METHODS ARE POWERFUL
# HAVING ALL CODE IN PYTHON DISTRIBUTION WOULD NOT BE GOOD
# HUGE CODE BASE: MESSY AND WITH CODE YOU WON'T USE
# MAINTENANCE ISSUES DEALING WITH SO MUCH CODE

# PACKAGES ARE A DIRECTORY OF PYTHON SCRIPTS
# EACH SCRIPT IS A MODULE
# THESE SPECIFY FUNCTIONS, METHODS, AND TYPES

# SOME PACKAGES FOR DATA SCIENCE INCLUDE:
# _______________________________________
# NUMPY - EFFICIENTLY WORKING WITH ARRAYS
# MATPLOTLIB - DATA VISUALIZATION
# SCIKIT-LEAR - MACHINE LEARNING

# USE PIP TO DOWNLOAD PACKAGES, AND IMPORT THEM AS NEEDED

# IMPORT NUMPY
import numpy
print(numpy.array([1, 2, 3]))  # CREATE ARRAY WITH NUMPY

# IMPORT MATH
import math
r = 0.43  # RADIUS
C = 2 * math.pi * r  # CIRCUMFERENCE
A = math.pi * r**2  # AREA

print(C)
print(A)

# RADIUS
radius = 192500

# TRAVEL DISTANCE OF MOON INF 12 DEGREES
distance = radius * math.radians(12)  # CONVERT 12 DEGREES TO RADIANS

print(distance)

